import os
from datetime import timedelta

CWD = os.path.abspath(os.path.dirname(__name__))

DEBUG = True
SECRET_KEY = "i am a secret key should be generated by random string"
PERMANENT_SESSION_LIFETIME = timedelta(days=14)

LOGGER_FILENAME = ""

SQLALCHEMY_DATABASE_URI = "sqlite:///" + os.path.join(CWD, "sso.db")

try:
    from config_local import *
except ImportError:
    pass
